// All Uzbek UI strings go here — never hardcode strings in components.
export const UZ = {
  roles: {
    admin: 'Administrator',
    rector: 'Rektor',
    'vice-rector': 'Prorektor',
    dean: 'Dekan',
    'department-head': 'Kafedra mudiri',
    teacher: "O'qituvchi",
    professor: 'Professor',
    methodologist: 'Metodist',
    student: 'Talaba',
    postgraduate: 'Magistrant',
    hr: "Kadrlar bo'limi",
    finance: "Moliya bo'limi",
    librarian: 'Kutubxonachi',
    'exam-coordinator': 'Imtihon koordinatori',
    counselor: 'Konsultant',
  },
  common: {
    dashboard: 'Bosh sahifa',
    login: 'Kirish',
    logout: 'Chiqish',
    loading: 'Yuklanmoqda...',
    error403: "Ruxsat yo'q",
    error404: 'Sahifa topilmadi',
    systemNameLine1: "TA'LIM MENEJMENT",
    systemNameLine2: 'AXBOROT TIZIMI',
  },
  landing: {
    subtitle: "BOJXONA INSTITUTIDA TA'LIM OLISH",
    subtitleLine1: 'BOJXONA INSTITUTIDA',
    subtitleLine2: "TA'LIM OLISH",
    title: 'PLATFORMASI',
    login: 'Kirish',
    guide: "Qo'llanma",
  },
  auth: {
    welcome: "Tizimga kirish",
    welcomeTitle: 'XUSH KELIBSIZ!',
    subtitle: "Email yoki foydalanuvchi nomi va parolingizni kiriting",
    username: "Foydalanuvchi nomi",
    password: 'Parol',
    usernamePlaceholder: "Foydalanuvchi nomini kiriting",
    passwordPlaceholder: 'Parolni kiriting',
    usernameRequired: "Foydalanuvchi nomini kiriting",
    passwordRequired: 'Parolni kiriting',
    remember: "Eslab qolish",
    rememberMe: 'Meni eslab qol',
    forgot: "Parolni unutdingizmi?",
    forgotPassword: "Parolni unutdim?",
    quote: "VATANGA MUHABBAT MAVHUM TUSHUNCHA BO'LMAY, TASHKILOTCHILIKNI, TARAQQIYOT VA MADANIYATNI TALAB QILADIGAN REAL RUHIY QUDRATDIR.",
  },
} as const;
