// All Uzbek UI strings go here — never hardcode strings in components.
export const UZ = {
  roles: {
    admin: 'Administrator',
    rector: 'Rektor',
    'vice-rector': 'Prorektor',
    dean: 'Dekan',
    'department-head': 'Kafedra mudiri',
    teacher: "O'qituvchi",
    professor: 'Professor',
    methodologist: 'Metodist',
    student: 'Talaba',
    postgraduate: 'Magistrant',
    hr: "Kadrlar bo'limi",
    finance: "Moliya bo'limi",
    librarian: 'Kutubxonachi',
    'exam-coordinator': 'Imtihon koordinatori',
    counselor: 'Konsultant',
    head: 'Boshliq',
  },
  common: {
    dashboard: 'Bosh sahifa',
    login: 'Kirish',
    logout: 'Chiqish',
    loading: 'Yuklanmoqda...',
    error403: "Ruxsat yo'q",
    error404: 'Sahifa topilmadi',
    systemNameLine1: "TA'LIM MENEJMENT",
    systemNameLine2: 'AXBOROT TIZIMI',
  },
  landing: {
    subtitle: "BOJXONA INSTITUTIDA TA'LIM OLISH",
    subtitleLine1: 'BOJXONA INSTITUTIDA',
    subtitleLine2: "TA'LIM OLISH",
    title: 'PLATFORMASI',
    login: 'Kirish',
    guide: "Qo'llanma",
  },
  auth: {
    welcome: "Tizimga kirish",
    welcomeTitle: 'XUSH KELIBSIZ!',
    subtitle: "Email yoki foydalanuvchi nomi va parolingizni kiriting",
    username: "Foydalanuvchi nomi",
    password: 'Parol',
    usernamePlaceholder: "Foydalanuvchi nomini kiriting",
    passwordPlaceholder: 'Parolni kiriting',
    usernameRequired: "Foydalanuvchi nomini kiriting",
    passwordRequired: 'Parolni kiriting',
    remember: "Eslab qolish",
    rememberMe: 'Meni eslab qol',
    forgot: "Parolni unutdingizmi?",
    forgotPassword: "Parolni unutdim?",
    quote: "VATANGA MUHABBAT MAVHUM TUSHUNCHA BO'LMAY, TASHKILOTCHILIKNI, TARAQQIYOT VA MADANIYATNI TALAB QILADIGAN REAL RUHIY QUDRATDIR.",
  },
  head: {
    selectCourse: 'Kursni tanlang',
    academicYear: "O'quv yili",
    time: 'Vaqt',
    schedule: 'Dars jadvali',
  },
  darsJadvali: {
    pageTitle: 'DARS JADVALI',
    boshSahifa: 'Bosh sahifa',
    royxatgaOlish: "Ro'yxatga olish",
    elektronJurnal: 'Elektron jurnal',
    komplekslar: 'Komplekslar',
    profil: 'Profil',
    hisobotlar: 'Hisobotlar',
    kursantlar: 'Kursant/Tinglovchilar',
    baholash: 'Baholash hisobotlari',
    xabarlar: 'Xabarlar',
    savolJavob: 'Savol-javoblar',
    aatDasturlari: "AAT dasturlari (o'quv)",
    oquvYili: "O'quv yili",
    oquvYiliTanlang: "O'quv yili tanlang",
    kursniTanlang: 'Kursni tanlang',
    haftaKunlariTanlang: 'Hafta kunini tanlang',
    kursOptions: ['1-kurs', '2-kurs', '3-kurs', '4-kurs'],
    vaqt: 'Vaqt',
    scheduleImagePlaceholder: 'Dars jadvali superadmin tomonidan yuklanadi',
    userName: 'Obidov Obid',
    userRole: "Inson resurslarini rivojlantirish va boshqarish bo'limi",
    maruza: "ma'ruza",
    seminar: 'seminar',
    laboratoriya: 'laboratoriya',
    amaliy: 'amaliy',
    days: ['Dushanba', 'Seshanba', 'Chorshanba', 'Payshanba', 'Juma', 'Shanba'],
    uzMonths: ['Yanvar', 'Fevral', 'Mart', 'Aprel', 'May', 'Iyun', 'Iyul', 'Avgust', 'Sentabr', 'Oktabr', 'Noyabr', 'Dekabr'],
    timeSlots: ['08:30–09:50', '10:00–11:20', '11:30–12:50', '14:00–15:20', '15:30–16:50'],
  },
  royxatgaOlish: {
    pageTitle: "RO'YXATGA OLISH",
    section1: "UMUMIY MA'LUMOT",
    section2: 'ISH JOYI VA LAVOZIMI',
    foto: 'Foto',
    fotoUpload: 'Foydalanuvchi rasmini yuklang',
    fotoFormat: '(jpg, jpeg, png formatda)',
    jshshir: 'JSHSHIR',
    jshshirPlaceholder: 'Foydalanuvchi JShShIRini kiriting',
    fio: 'F.I.O',
    fioPlaceholder: 'Obidov Obid Xusanovich',
    malumoti: "Ma'lumoti",
    malumotiOptions: ["O'rta", "O'rta-maxsus", 'Oliy', 'Tugallanmagan oliy'],
    pasport: "Pasport ma'lumotlari",
    pasportPlaceholder: 'Pasport seriyasi va raqami',
    berilganSana: 'Berilgan sana',
    jinsi: 'Jinsi',
    jinsOptions: ['Erkak', 'Ayol'],
    tugilganSana: "Tug'ilgan sanasi",
    millati: 'Millati',
    millatOptions: ["O'zbek", 'Qozoq', 'Rus', 'Tojik', "Qirg'iz"],
    kimTomonidan: 'Kim tomonidan berilgan',
    fuqaroligi: 'Fuqaroligi',
    fuqaroligiOptions: ["O'zbekiston", 'Qozogiston', 'Rossiya', 'Tojikiston', "Qirg'iziston"],
    telefon: 'Telefon raqami',
    pochta: 'Pochta manzili',
    tarkibiyTuzilma: 'Tarkibiy tuzilma',
    tarkibiyOptions: ['Kafedra', "Bo'lim", 'Fakultet', 'Dekanat'],
    lavozimi: 'Lavozimi',
    lavozimOptions: [
      'Mavjud emas', 'Kichik inspektor', 'Inspektor', 'Katta inspektor',
      'Bosh inspektor', "Bo'lim boshlig'i", "Markaz boshlig'i",
      'Boshliq', "Boshliq o'rinbosari", "O'qituvchi",
      "Kafedra boshlig'i", "Fakultet boshlig'i",
    ],
    ilmiyUnvoni: 'Ilmiy unvoni',
    ilmiyUnvoniOptions: [
      'Mavjud emas', 'Assistent', "O'qituvchi", "Katta o'qituvchi",
      'Dotsent', 'Professor', 'Akademik',
    ],
    ilmiyDarajasi: 'Ilmiy darajasi',
    ilmiyDarajasiOptions: [
      'Mavjud emas', 'Bakalavr', 'Magistr',
      'Falsafa doktori (PhD)', 'Fan doktori (DSc)',
    ],
    guvohnomaRaqami: 'Guvohnoma raqami (udastreniya)',
    guvohnomaPlaceholder: 'MT5766',
    harbiyUnvoni: 'Harbiy unvoni',
    harbiyUnvoniOptions: [
      'Mavjud emas', 'Katta serjant', 'Leytenant', 'Katta leytenant',
      'Kapitan', 'Mayor', 'Podpolkovnik', 'Polkovnik',
    ],
    tanlang: 'Tanlang',
    saqlash: 'Saqlash',
    jshshirError: '14 ta raqam kiriting',
    pasportError: 'Format: AA1234567 (2 harf + 7 raqam)',
    majburiy: 'Majburiy maydon',
    emailError: "To'g'ri email manzil kiriting",
  },
  tinglovchilar: {
    pageTitle: 'TINGLOVCHILAR',
    qoshish: "Tinglovchi qo'shish",
    oquvYili: "O'quv yili",
    oquvGuruhi: "O'quv guruhi",
    fish: 'Tinglovchi F.I.SH',
    jinsi: 'Jinsi',
    tr: 'T/r',
    avval: 'Avval',
    keyin: 'Keyin',
    oquvYiliOptions: ['2023-2024-yil', '2024-2025-yil', '2025-2026-yil'],
    guruhOptions: ['MBH-123', 'MBH-223', 'MBH-323', 'MBI-123', 'MBI-223', 'MBI-323'],
    jinsOptions: ['Erkak', 'Ayol'],
    tinglovchiQoshishTitle: "TINGLOVCHI MA'LUMOTLARI",
    viewTitle: "TINGLOVCHI HAQIDA MA'LUMOTLAR",
    tahrirlash: 'Tahrirlash',
    harbiyLavozimiLabel: 'Harbiy lavozimi',
    harbiyLavozimiOptions: ['Leytenant', 'Katta leytenant', 'Kapitan', 'Mayor', 'Podpolkovnik', 'Polkovnik'],
    guvohnomaRaqamiLabel: 'Guvohnoma raqami',
    guvohnomaPlaceholder: 'Kiriting',
    guruhiLabel: 'Guruhi',
    guruhiPlaceholder: 'Namuna: MBH-125, MBI-225',
  },
  kursantlar: {
    pageTitle: 'KURSANTLAR',
    menuLabel: 'Kursantlar',
    tinglovchilarLabel: 'Tinglovchilar (magistratura)',
    qoshish: "Kursant qo'shish",
    oquvYili: "O'quv yili",
    kurs: 'Kurs',
    oquvGuruhi: "O'quv guruhi",
    fish: 'Kursant F.I.SH',
    jinsi: 'Jinsi',
    tr: 'T/r',
    avval: 'Avval',
    keyin: 'Keyin',
    oquvYiliOptions: ['2023-2024-yil', '2024-2025-yil', '2025-2026-yil'],
    kursOptions: ['1-kurs', '2-kurs', '3-kurs', '4-kurs'],
    guruhOptions: ['BI-123', 'BI-223', 'BI-323', 'BI-423', 'BI-523', 'YUP-123', 'YUP-223'],
    jinsOptions: ['Erkak', 'Ayol'],
    kursiPlaceholder: 'Kursi: 3-kurs',
    guruhPlaceholder: "O'quv guruhi: BI-323",
    kursantQoshishTitle: "KURSANT MA'LUMOTLARI",
    viewTitle: "KURSANT HAQIDA MA'LUMOTLAR",
    tahrirlash: 'Tahrirlash',
    harbiyUnvoniLabel: 'Harbiy unvoni',
    guvohnomaRaqamiLabel: 'Guvohnoma raqami',
    kursiLabel: 'Kursi',
    guruhiLabel: 'Guruhi',
    lavozimLabel: 'Lavozimi',
    harbiyUnvoniOptions: ['Kursant'],
    guruhiPlaceholder: 'Namuna: 125-guruh',
    guruhiOptions: ['125-guruh', '225-guruh', '325-guruh', '425-guruh'],
    lavozimOptions: ["Ega emas", "Bo'linma sardori", 'Guruh sardori', 'Kurs sardori'],
  },
  hisobotlar: {
    pageTitle: 'HISOBOTLAR',
    menuLabel: 'Hisobotlar',
    sutkalikNaryadlar: "Sutkalik naryadlar bo'yicha",
    institutChiqish: 'Institut hududidan chiqish bo\'yicha',
    kasalKursantlar: 'Kasal kursantlar',
    subTitleSutkalik: "SUTKALIK NARYADLAR BO'YICHA",
    subTitleInstitut: "INSTITUT HUDUDIDAN CHIQISH BO'YICHA",
    subTitleKasal: 'KASAL KURSANTLAR',
    oquvYili: "O'quv yili",
    oy: 'Oy',
    kurs: 'Kurs',
    guruh: 'Guruh',
    fish: 'Kursant F.I.SH',
    xizmatOtashJoyi: "Xizmat o'tash joyi",
    qabulQilishSanasi: 'Qabul qilish sanasi',
    topshirishSanasi: 'Topshirish sanasi',
    tashqarigaChiqishSababi: 'Tashqariga chiqish sababi',
    chiqishSanasi: 'Chiqish sanasi',
    jins: 'Jins',
    kasallikSababi: 'Kasallik sababi/Izoh',
    kiritilganSana: 'Kiritilgan sana',
    murojaatVaqti: 'Murojaat vaqti',
    kasalYuborilanJoy: 'Kasal yuborilgan joy',
    boshlanishSanasi: 'Boshlanish sanasi',
    tugashSanasi: 'Tugash sanasi',
    tr: 'T/r',
    guruhi: 'Guruhi',
    avval: 'Avval',
    keyin: 'Keyin',
    oquvYiliOptions: ['2023-2024-y', '2024-2025-y', '2025-2026-y'],
    oyOptions: ['Yanvar','Fevral','Mart','Aprel','May','Iyun','Iyul','Avgust','Sentabr','Oktabr','Noyabr','Dekabr'],
    kursOptions: ['1-kurs', '2-kurs', '3-kurs', '4-kurs'],
    guruhOptions: ['125-guruh', '225-guruh', '325-guruh', '425-guruh', '525-guruh'],
    xizmatJoyOptions: [
      "1-NO'J bo'yicha navbatchi",
      "1-NO'J bo'yicha navbatchi yordamchisi",
      "1-NO'J bo'yicha 1-posbon",
      "1-NO'J bo'yicha 2-posbon",
      "2-NO'J bo'yicha navbatchi",
      "2-NO'J bo'yicha navbatchi yordamchisi",
      "2-NO'J bo'yicha posbon",
      'Navbatchi yordamchisi',
      "O'quv bino bo'yicha navbatchi",
      "O'quv bino bo'yicha navbatchi yordamchisi",
      "1-yotoqxona bo'yicha navbatchi",
      "1-yotoqxona bo'yicha navbatchi yordamchisi",
      "1-yotoqxona bo'yicha posbon",
      "2-yotoqxona bo'yicha navbatchi",
      "2-yotoqxona bo'yicha navbatchi yordamchisi",
      "2-yotoqxona bo'yicha posbon",
      "Institut bo'yicha 1-patrul",
      "Institut bo'yicha 2-patrul",
      "Institut bo'yicha 3-patrul",
      "Institut bo'yicha 4-patrul",
      "Qizlar yotoqxonasi bo'yicha navbatchi",
      "Qizlar yotoqxonasi bo'yicha posbon",
    ],
    chiqishSababOptions: [
      'Navbatdagi uvalneniya',
      "Rag'bat / navbatdan tashqari uvalneniya",
      'Kasal / poliklinika',
      'Boshqa sabab',
    ],
    kasalJoyOptions: ['Poliklinika', 'Gospital', 'Tibbiyot punkti', 'Yotoqxona'],
    jinsOptions: ['Erkak', 'Ayol'],
    topshirishError: "Topshirish sanasi qabul qilish sanasidan kamida 1 kun keyin bo'lishi kerak",
  },
} as const;
